### ISSUE TITLE
Why not to re-export HaskellNet modules?

### ISSUE THREAD

**Issue by lemol** [dpwright/HaskellNet-SSL#10]
For example, instead of doing:

```haskell
import Network.HaskellNet.IMAP
import Network.HaskellNet.IMAP.SSL
import Network.HaskellNet.Auth
```

just do

```haskell
import Network.HaskellNet.IMAP.SSL
```

**Comment by dpwright** [comment]
That seems reasonable... certainly re-exporting `Network.HaskellNet.IMAP` seems like a fair enough thing to do.  I'm not sure about `Network.HaskellNet.Auth` -- if it's going to be re-exported by anything it makes sense to me that `Network.HaskellNet.IMAP` should do that, and then if `Network.HaskellNet.IMAP.SSL` re-exports *that* it'll get `Auth` naturally.

So I would be in favour of:

1. Re-exporting `Network.HaskellNet.IMAP` from `Network.HaskellNet.IMAP.SSL`
2. Submitting a pull request to HaskellNet to re-export `Network.HaskellNet.Auth` from `Network.HaskellNet.IMAP`

I'm a bit busy at the moment to do that myself, but I'll happily merge a pull request along these lines... otherwise I'll just stick it in next time I'm updating HaskellNet-SSL.

**Comment by lemol** [comment]
Yes, I think this reasonable too.

And also re-export  `Network.HaskellNet.SSL` (or maybe just the `Settings` data type in it) in each protocol specific method.

For `Network.HaskellNet.Auth` I think it is sufficient just to re-export `AuthType`.
