### ISSUE TITLE
gmail login example not working

### ISSUE THREAD

**Issue by maerten** [dpwright/HaskellNet-SSL#19]
Hi,

the SMTP.authenticate action returns false when I'm logged in to Gmail over SMTP (TLS or SSL). I suspect this has something to do with HaskellNet, or maybe it's a combination of using SMTP with SSL.

If there is anything I can do to help solving this issue, please let me know!

**Comment by maerten** [comment]
Closing, I guess it had to do with Google's security settings, not the library itself.

**Comment by dpwright** [comment]
Yeah, this was reported a while back on haskell-cafe -- the reason is that Google now calls any app which doesn't use OAuth 2 "insecure", and by default disables it for accounts not using two-factor authentication.  You can re-enable it here:

https://www.google.com/settings/security/lesssecureapps

I think normal password logins do work if you have 2FA enabled and you generate an app-specific password for your account, so if you don't want to enable a setting called "allow less secure apps to access my account" (!), you could do that instead.

I have started work on connecting with OAuth 2, though currently that's just locally on my machine and not pushed yet, and it's taken a bit of a back-seat to other work I have going on.  I may push the branch in the state it's currently in, in case anyone else wants to get it working...

**Comment by maerten** [comment]
I havent found another haskell lib that provides easy Gmail with OAuth 2 yet, and it would be nice to avoid 2FA for this particular app I'm building (it uses a shared gmail account). So I would be very interested to try it out for the next version of the app I'm working on.

At the very least I could test out your oAuth 2 branch and report the results.

Thanks!

**Comment by dpwright** [comment]
OK, I've pushed my WIP commit here: https://github.com/dpwright/HaskellNet/commit/fa1c7cbe6a31c583c3bba1c54b08ce996a05f26c

I'd forgotten, but as this is nothing to do with SSL/TLS the change required is to jdaugherty/HaskellNet, not HaskellNet-SSL.  The code in that commit looks like it should work according to the spec, but the server returned an error when I tested it.  I didn't spend an awful lot of time with it.

I think I'll reopen this issue while we're talking about it, in case anybody else has trouble with the gmail example...

**Comment by auermich93** [comment]
There is a logical error in the code. If authentication works, it will always print: "Authentication error."
The if-statement is wrong. Add 'not' before 'authSucceed', then it will work. Moreover, as above suggested, it is mandatory to enable access from less secure apps, otherwise an exception will be thrown.

```
smtpTest = doSMTPSTARTTLS "smtp.gmail.com" $ \c -> do
    authSucceed <- SMTP.authenticate LOGIN username password c
    if (**not** authSucceed)
      then print "Authentication error."
      else sendPlainTextMail recipient username subject body c
  where subject = "Test message"
body = "This is a test message"
```

**Comment by Hazelfire** [comment]
I will close this issue as it's not related to this repository, and requires using OAuth. If anyone is interested in accessing Gmail without enabling access to "insecure apps", https://hackage.haskell.org/package/gogol-gmail looks promising. If you want to use IMAP/SMTP/HaskellNet using OAuth, I'd recommend opening a related issue in https://github.com/jtdaugherty/HaskellNet.
